### ISSUE TITLE
Cannot run in Mac M1

### ISSUE THREAD

**Issue by phamthainb** [py-pdf/PyPDF2#1074]
On my Mac M1, I cannot import PyPDF2

## Environment

```bash
$ python3 -m platform
macOS-12.3.1-arm64-arm-64bit

$ python3 -c "import PyPDF2;print(PyPDF2.__version__)"
# Got Error here
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/PyPDF2/__init__.py", line 10, in <module>
    from ._encryption import PasswordType
  File "/opt/homebrew/lib/python3.9/site-packages/PyPDF2/_encryption.py", line 59, in <module>
    from Crypto.Cipher import AES, ARC4  # type: ignore[import]
  File "/opt/homebrew/lib/python3.9/site-packages/Crypto/Cipher/__init__.py", line 82, in <module>
    from Crypto.Cipher._mode_ctr import _create_ctr_cipher
  File "/opt/homebrew/lib/python3.9/site-packages/Crypto/Cipher/_mode_ctr.py", line 35, in <module>
    from Crypto.Util.number import long_to_bytes
  File "/opt/homebrew/lib/python3.9/site-packages/Crypto/Util/number.py", line 398
    s = pack('>I', n & 0xffffffffL) + s
                                 ^
SyntaxError: invalid syntax
```

**Comment by MasterOdin** [comment]
What version of `PyCryptodome` are you using? You should be able to see it by doing `python3 -m pip list`.

**Comment by phamthainb** [comment]
> PyCryptodome

It's here
```
python3 -m pip list | grep "pycryptodome"
pycryptodome             3.4.3
```

**Comment by MasterOdin** [comment]
Are you able to update to the latest version (3.15.0)?

```
python3 -m pip install -U pycryptodome
```

**Comment by phamthainb** [comment]
> Are you able to update to the latest version (3.15.0)?
> 
> ```
> python3 -m pip install -U pycryptodome
> ```

Thanks u, It's work perfect
