### ISSUE TITLE
cmap handling: failure when a `beginbfchar` pair has a zero-length second element

### ISSUE THREAD

**Issue by dkg** [py-pdf/PyPDF2#1111]
I'm building a pdf file with weasyprint that has both english and arabic characters in it.  The contents of [habibi.html](https://github.com/py-pdf/PyPDF2/files/9114540/habibi.html.txt) are:

```html
<!DOCTYPE html>
<head>
<meta charset="utf-8">
<title>habibi</title>
</head>
<body>
<div>حَبيبي habibi</div>
</body>
</html>
```

## Environment

I build this with weasyprint 54.1-3 (on debian unstable)

```bash
$ weasyprint habibi.html habibi.pdf
```

This results in [habibi.pdf](https://github.com/py-pdf/PyPDF2/files/9114548/habibi.pdf).

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
# Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0] on linux
# Type "help", "copyright", "credits" or "license" for more information.
>>> from PyPDF2 import PdfReader
>>> r = PdfReader('habibi.pdf')
>>> r.pages[0].extract_text()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/PyPDF2/_page.py", line 1316, in extract_text
    return self._extract_text(self, self.pdf, space_width, PG.CONTENTS)
  File "/usr/lib/python3/dist-packages/PyPDF2/_page.py", line 1129, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
  File "/usr/lib/python3/dist-packages/PyPDF2/_cmap.py", line 21, in build_char_map
    map_dict, space_code, int_entry = parse_to_unicode(ft, space_code)
  File "/usr/lib/python3/dist-packages/PyPDF2/_cmap.py", line 246, in parse_to_unicode
    ] = unhexlify(lst[1]).decode(
IndexError: list index out of range
>>> 
```

This appears to be because `habibi.pdf` contains this stream:

```
stream
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo
<< /Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>> def
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <ffff>
endcodespacerange
6 beginbfchar
<0003> <>
<03f2> <>
<0392> <>
<03f4> <>
<02f4> <>
<03a3> <062d064e0628064a0628064a0020>
endbfchar
endcmap
CMapName currentdict /CMap defineresource pop
end
end
endstream
```
The handling in `parse_to_unicode` in `_cmap.py` appears buggy because it can't handle these lines that have an empty anglebracket as the second stage.

(feel free to include `habibi.pdf` in your test suite of course!)

(this is related to #1110, which i offered on the way to finding this simpler test case)

**Comment by dkg** [comment]
After #1110 is applied, the code sample above doesn't crash, but it yields:

```
'حَبيبي habibi\x03ϲΒϴΒ˴ حَبيبي '
```
I'd have expected it to yield something like:

```
حَبيبي habibi
```

**Comment by dkg** [comment]
The more i look at this, and the more i read of the PDF specification (and [adobe technical note 5014](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5014.CIDFont_Spec.pdf)), the more i think this needs a proper grammar instead of string manipulation.

That said, i'm not prepared to write or offer such a fix, so i'm instead offering a hackish workaround for now at #1118.  I'm afraid it increases the technical debt of the project, but it also makes it not crash when reading a pdf that's relatively easy to create.

**Comment by dkg** [comment]
I think this bug should be tagged with MCVE, since `habibi.pdf` is a minimal reproducer.
