### ISSUE TITLE
Exception when merging PDF with bookmarks

### ISSUE THREAD

**Issue by technillogue** [py-pdf/PyPDF2#133]
Hello, I'm using reportlab+PyPDF2 to add hyperlinks to an existing PDF. When I try to merge the PDF and a reportlab-made PDF containing links and bookmarks, I get the following error:

```
Traceback (most recent call last):
  File "pdflinker.py", line 257, in <module>
    PDF(**args).main()
  File "pdflinker.py", line 64, in main
    output_writer.write(self.dest_pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 315, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 389, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 389, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 409, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/pdf.py", line 1378, in getObject
    retval = readObject(self.stream, self)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/generic.py", line 63, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/generic.py", line 569, in readFromStream
    value = readObject(stream, pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/generic.py", line 68, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/generic.py", line 162, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/generic.py", line 95, in readObject
    return NumberObject.readFromStream(stream)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/generic.py", line 269, in readFromStream
    return NumberObject(num)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2-1.23-py2.7.egg/PyPDF2/generic.py", line 247, in __new__
    return int.__new__(cls, value)
ValueError: invalid literal for int() with base 10: '0,'
```

Any suggestions? It would seem that PyPDF is literally trying to read off a int from the stream and snagging a comma with it.

**Comment by MartinThoma** [comment]
I've just adjusted the code to be more easy to execute:

```python
from PyPDF2 import PdfReader, PdfWriter

def merge_with(input_pdf, overlay_file, debug_overlay=True):
    """
    overlay_file: The file to merge with
    Read original and passed file into PyPDF, and merge them into
    output_writer
    Returns: output_writer
    """
    print("Reading input file...")
    input_pdf_reader = PdfReader(input_pdf)
    
    print("Reading overlay file...")
    overlay_pdf_reader = PdfReader(overlay_file)
    output_writer = PdfWriter()
    for page_no, page in enumerate(input_pdf_reader.pages):
        # Superimpose the overlay PDF over the original.
        print(f"Merging pages no {page_no}")
        page.merge_page(overlay_pdf_reader.pages[page_no])
        if debug_overlay:
            output_writer.add_page(overlay_pdf_reader.pages[page_no])
        else:
            output_writer.add_page(page)
    return output_writer

merge_with("tstwith.pdf", "tstwithout.pdf")
```

**Comment by MartinThoma** [comment]
I don't see an exception, so I close this. If you happen to see this issue again, please let me know.
