### ISSUE TITLE
(Edit Annotation) ValueError: Key Must Be PdfObject

### ISSUE THREAD

**Issue by Cameron-Leech-Thomson** [py-pdf/PyPDF2#1378]
Hey, I'm pretty sure it's just because I'm doing something wrong but I can't seem to change the value of an annotation, and end up with the same error:
```
Traceback (most recent call last):
  File "D:\Documents\Other Projects\D&D Bot\Discord.py\example_bot.py", line 133, in on_message
    success = setField(path + attachment.filename, messageValues[1], messageValues[2])
  File "D:\Documents\Other Projects\D&D Bot\Discord.py\pdfReader.py", line 63, in setField
    annotation["/V"] = value
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic\_data_structures.py", line 136, in __setitem__
    raise ValueError("key must be PdfObject")
ValueError: key must be PdfObject
```

The code that caused the error is:
```python
def setField(path, key, value):
    success = False
    pdf = PyPDF2.PdfFileReader(path)
    
    writer = PyPDF2.PdfFileWriter()
    writer.clone_document_from_reader(pdf)
    
    for i in range(writer.getNumPages()):
        if "/Annots" in writer.pages[i]:
            # Get annotations from page:
            for anno in writer.pages[i]["/Annots"]:
                annotation = anno.get_object()
                # Check if the target exists in the annotations:
                if key.lower() == str(annotation["/T"]).strip().lower().replace(' ', ''):
                    # Update the field:
                    if "/V" in annotation:
                        print(type(annotation["/V"]))
                        annotation["/V"] = value           <------ here
                        writer.add_annotation(i, annotation)
                        success = True
    
    if (success):
        with open (path, 'wb') as output_stream:
            writer.write(output_stream)
    
    return success
```

If there's an easier way to change the value of an annotation I'd love to know, but this is about as good as I could manage. I couldn't really find any mention of editing the annotations in the docs so if I was looking in the wrong place please let me know

The PDF I'm using is attached. Thanks
[Cammyyy_79897300.pdf](https://github.com/py-pdf/PyPDF2/files/9697388/Cammyyy_79897300.pdf)

_Originally posted by @Cameron-Leech-Thomson in https://github.com/py-pdf/PyPDF2/issues/648#issuecomment-1265362359_

**Comment by Cameron-Leech-Thomson** [comment]
Turns out this is the way to do it:

```python
def setField(path, key, value):
    success = False
    pdf = PdfFileReader(path)
    
    writer = PdfFileWriter()
    writer.clone_document_from_reader(pdf)
    
    for i in range(writer.getNumPages()):
        if "/Annots" in writer.pages[i]:
            # Get annotations from page ("/Annots" is just an array of each annotation dict):
            for anno in writer.pages[i]["/Annots"]:
                annotation = anno.get_object()
                # Check if the target exists in the annotations:
                if key.lower() == str(annotation["/T"]).strip().lower().replace(' ', ''):
                    # Update the field:
                    if "/V" in annotation:
                        annotation.update(
                            {
                                NameObject("/V"): TextStringObject(value)
                            }
                        )
                        success = True
    
    if (success):
        with open (path, 'wb') as output_stream:
            writer.write(output_stream)
    
    return success
```

**Comment by pubpub-zz** [comment]
the PyPDF2 annotations need to be NameObject and values needs also to be converted (here a TextStringObject):
annotation[PyPDF2.generic.NameObject("/V")] = PyPDF2.generic.TextStringObject(value)

**Comment by Cameron-Leech-Thomson** [comment]
Thanks :)

**Comment by manfredima** [comment]
Could you please tell me how to change/delete the name of the _comment author_ contained in the **'/T'** object?
