### ISSUE TITLE
Destroyed text in ContentStream if illegal chars

### ISSUE THREAD

**Issue by JW1000111** [py-pdf/PyPDF2#256]
In the latest Version of PyPDF2 there is the following problem with the ContentStream:
If the ContentStream contains a character which is not included in the pdf_encoding (e.g.: é or ´), then a TextStringObject will be created in UTF16-BE. In the official PDF documentation is written that the ContentStream cannot contain Unicode strings. In the result you'll get a PDF with a destroyed ContentStream in which you cannot read the text anymore.

Possible solution:
Create the TextObject in the ContentStream in an other way.

**Comment by lxw0109** [comment]
I came across a similar problem, when processing a Chinese document(English document works well), the following error message will show:
```
Traceback (most recent call last):
  File "slicePdf.py", line 23, in <module>
    main()
  File "slicePdf.py", line 20, in main
    output.write(outputStream)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 572, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 572, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 557, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 572, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 580, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 1675, in getObject
    retval = readObject(self.stream, self)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 580, in readFromStream
    value = readObject(stream, pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 60, in readObject
    return NameObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 493, in readFromStream
    raise utils.PdfReadError("Illegal character in Name Object")
PyPDF2.utils.PdfReadError: Illegal character in Name Object
```
Anyone helps? : )

**Comment by allenbang** [comment]
@lxw0109 hi, did you solve this problem? I get this error also when process Chinese pdf.

**Comment by lxw0109** [comment]
@allenbang Sorry, I did not solve this problem.   : (

**Comment by kzhui125** [comment]
```py
inputpdf = PdfFileReader(open("1.pdf", "rb"), strict=False)
```

use strict=False

**Comment by Microndgt** [comment]
@kzhui125 but using `strict=False` makes pdf unreadable

**Comment by vvvhung** [comment]
With below file, though using `strict=False` make it pass but every character in output file of PdfFileWriter become rectangle (and even crash pdf software)
https://drive.google.com/file/d/1Fwy4Tj8q1xLP3mfONLPOb_ApoC0elioH/view?usp=sharing

**Comment by MartinThoma** [comment]
Does this issue still occur? Has somebody an example PDF showing it?

**Comment by MartinThoma** [comment]
As we cannot reproduce it, I assume it's solved.

Please let me know if you still see this issue with the latest version of PyPDF2, then I'll reopen.
