### ISSUE TITLE
python3 - ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by LeoFCardoso** [py-pdf/PyPDF2#267]
I am getting this error when using python3 and this simple code with a sample PDF (xSane generated).

output = PdfFileWriter()
imagepdf = PdfFileReader(open(sys.argv[1], 'rb'), strict=False)
textpdf = PdfFileReader(open(sys.argv[2], 'rb'), strict=False)
for i in range(imagepdf.getNumPages()):
    imagepage = imagepdf.getPage(i)
    textpage = textpdf.getPage(i)
    factor_x = textpage.mediaBox.upperRight[0] / imagepage.mediaBox.upperRight[0]
    factor_y = textpage.mediaBox.upperRight[1] / imagepage.mediaBox.upperRight[1]
    imagepage.scale(float(factor_x), float(factor_y))
    textpage.mergePage(imagepage)  # imagepage stay on top
    textpage.compressContentStreams()
    output.addPage(textpage)

Traceback (most recent call last):
  File ".../pdf2pdfocr_multibackground.py", line 34, in <module>
    imagepage.scale(float(factor_x), float(factor_y))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/pdf.py", line 2493, in scale
    0,  0])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/pdf.py", line 2479, in addTransformation
    originalContent, self.pdf, ctm)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/pdf.py", line 2180, in _addTransformationMatrix
    contents = ContentStream(contents, pdf)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/pdf.py", line 2645, in __init__
    self.**parseContentStream(stream)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/pdf.py", line 2677, in __parseContentStream
    operands.append(readObject(stream, None))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/generic.py", line 71, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/generic.py", line 166, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/generic.py", line 98, in readObject
    return NumberObject.readFromStream(stream)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/generic.py", line 269, in readFromStream
    return NumberObject(num)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyPDF2/generic.py", line 252, in __new**
    val = int(value)
ValueError: invalid literal for int() with base 10: b''

**Comment by MartinThoma** [comment]
If anybody has the same error, please open a new bug ticket and fill out the questionnaire there. Especially the example pdf is necessary.
