### ISSUE TITLE
Unable to find endstream marker in Leadtools PDF

### ISSUE THREAD

**Issue by TZanke** [py-pdf/PyPDF2#291]
Hello,

I discovered a problem with editing PDF Files created by Leadtools PDF.

While rotate and save a PDF file (to a new location) i get an Error:
`Exception Value: Unable to find 'endstream' marker after stream at byte 0x10ba5.`

Other PDF files, and some of the Leadtools PDFs, work as expected.

## MCVE
File for reproducing the Error: 
[leadtoolsdemo.pdf](https://github.com/mstamy2/PyPDF2/files/521358/leadtoolsdemo.pdf)

```python
import tempfile
import PyPDF2


reader = PyPDF2.PdfFileReader('leadtoolsdemo.pdf')
writer = PyPDF2.PdfFileWriter()

for page in reader.pages:
    writer.addPage(page)

file_tmp, file_path_tmp = tempfile.mkstemp('wb')
with open(file_tmp, 'wb') as pdf_out:
    writer.write(pdf_out)
```

**Comment by 14vv1A0516** [comment]
Even I am not able to write .
What could be the problem Sir

**Comment by MartinThoma** [comment]
With `PyPDF2==2.3.0` I get:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 725, in write
    self._sweep_indirect_references(external_reference_map, self._root)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 844, in _sweep_indirect_references
    self._sweep_indirect_references(extern_map, realdata)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 820, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 844, in _sweep_indirect_references
    self._sweep_indirect_references(extern_map, realdata)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 820, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 829, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, data[i])
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 844, in _sweep_indirect_references
    self._sweep_indirect_references(extern_map, realdata)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 820, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 820, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 820, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 867, in _sweep_indirect_references
    newobj = self._sweep_indirect_references(extern_map, newobj)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 820, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_writer.py", line 858, in _sweep_indirect_references
    newobj = data.pdf.get_object(data)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 1049, in get_object
    retval = read_object(self.stream, self)  # type: ignore
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1253, in read_object
    return DictionaryObject.read_from_stream(stream, pdf, forced_encoding)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 799, in read_from_stream
    "Unable to find 'endstream' marker after stream at byte "
PyPDF2.errors.PdfReadError: Unable to find 'endstream' marker after stream at byte 0x10ba5.
```

**Comment by pubpub-zz** [comment]
the test code uses PdfFileReader/PdfFileMerger instead of PdfReader/PdfMerger (strict=False in this case)
```
import tempfile
import PyPDF2


reader = PyPDF2.PdfReader('leadtoolsdemo.pdf')
writer = PyPDF2.PdfWriter()

for page in reader.pages:
    writer.addPage(page)

file_tmp, file_path_tmp = tempfile.mkstemp('wb')
with open(file_tmp, 'wb') as pdf_out:
    writer.write(pdf_out)
```
with this correction the test is good

This issue should be closed

**Comment by pubpub-zz** [comment]
+1?

**Comment by MartinThoma** [comment]
Thank you for the reminder @pubpub-zz :-)
