### ISSUE TITLE
Unexpected escaped string for a valid PDF.

### ISSUE THREAD

**Issue by kaplun** [py-pdf/PyPDF2#360]
Given the PDF available at: https://export.arxiv.org/pdf/1707.04066v1
the current snippet:
```python
import PyPDF2
pdf = PyPDF2.PdfFileReader("/tmp/1707.04066v1")
pdf.getNamedDestinations()
```
will crash with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1312, in getNamedDestinations
    self.getNamedDestinations(kid.getObject(), retval)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 178, in getObject
    return self.pdf.getObject(self).getObject()
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 579, in readFromStream
    value = readObject(stream, pdf)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 71, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 166, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 77, in readObject
    return readStringFromStream(stream)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 390, in readStringFromStream
    raise utils.PdfReadError(r"Unexpected escaped string: %s" % tok)
PyPDF2.utils.PdfReadError: Unexpected escaped string: h
```

This is with the latest stable release available on PyPI and the latest master

**Comment by MartinThoma** [comment]
I can confirm with `PyPDF2==1.27.7`:

```
Traceback (most recent call last):
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 381, in readStringFromStream
    tok = ESCAPE_DICT[tok]
KeyError: b'h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "issue459.py", line 3, in <module>
    pdf.getNamedDestinations()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1436, in getNamedDestinations
    self.getNamedDestinations(kid.getObject(), retval)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 191, in getObject
    return self.pdf.getObject(self).getObject()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1739, in getObject
    retval = readObject(self.stream, self)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 79, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 602, in readFromStream
    value = readObject(stream, pdf)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 84, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 181, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 90, in readObject
    return readStringFromStream(stream)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 407, in readStringFromStream
    raise PdfReadError(r"Unexpected escaped string: %s" % tok)
PyPDF2.errors.PdfReadError: Unexpected escaped string: b'h'
```
