### ISSUE TITLE
KeyError: '/Type' when trying to PdfFileReader(fp)

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/PyPDF2#388]
```
from PyPDF2 import PdfFileReader

with open(pdf_path, 'rb') as fp:
    pdf_toread = PdfFileReader(fp)
```

gives

```
Traceback (most recent call last):
  File "/home/math/.local/bin/edapy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/math/Github/edapy/bin/edapy", line 44, in <module>
    entry_point()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/math/Github/edapy/edapy/pdf.py", line 58, in find
    data.append(get_pdf_info(pdf_path))
  File "/home/math/Github/edapy/edapy/pdf.py", line 87, in get_pdf_info
    pdf_toread = PdfFileReader(fp)
  File "/usr/local/lib/python3.5/dist-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/usr/local/lib/python3.5/dist-packages/PyPDF2/pdf.py", line 1805, in read
    assert xrefstream["/Type"] == "/XRef"
  File "/usr/local/lib/python3.5/dist-packages/PyPDF2/generic.py", line 516, in __getitem__
    return dict.__getitem__(self, key).getObject()
KeyError: '/Type'
```

## Reproducing the error
I may not share the PDF file. I can open it without any problems with Atril Document Viewer 1.12.2

If you have a lot of PDF files, you could install my tool [`edapy`](https://github.com/MartinThoma/edapy) which uses PyPDF2 internally. You can run it with

```
$ edapy pdf find --path directory/with/many/pdfs --output out.csv
```

## System

* Ubuntu 16.04

```
>>> import PyPDF2
>>> PyPDF2.__version__
'1.26.0'
```

**Comment by SalilVishnuKapur** [comment]
It is working for me. I think you have some issue with your system or something else.

**Comment by MartinThoma** [comment]
@SalilVishnuKapur I ran this on ~30,000 PDFs and had this error for ~3 PDFs. On how many PDFs did you try it?

**Comment by SalilVishnuKapur** [comment]
@MartinThoma Interesting. I ran it for just 1 Interactive pdf, but the issue might be with those 3 pdfs, as in the format in actual might be something else or there can be multiple reasons for the same.

**Comment by Wolfium** [comment]
I am suffering same issue with one specific PDF file with in fact works on Linux, with this library same version on Windows, same input file (shared thru docker volumes) fails with this kind of error.

Looks like something not cross platform

```
  File "c:\ARSAT\GIT\desa\arsat.emple.portal\bknd\tests\integration.py", line 261, in test_1_1_login_upload_download_defaultPass
    doc = PdfFileReader(open('out.pdf', 'rb'))
  File "c:\ARSAT\GIT\desa\arsat.emple.portal\ENV\lib\site-packages\PyPDF2\pdf.py", line 1084, in __init__
    self.read(stream)
  File "c:\ARSAT\GIT\desa\arsat.emple.portal\ENV\lib\site-packages\PyPDF2\pdf.py", line 1805, in read
    assert xrefstream["/Type"] == "/XRef"
TypeError: 'NumberObject' object has no attribute '__getitem__
```

Look related to #185 

Any help appreciated

**Comment by AzizieAbuduaini** [comment]
I am suffering the same issue with one specific PDF file which was created and stored in s3. But when I try to read specific pdf then I got the above error. I assume PdfFileReader try to read the content of pdf which contains special characters

**Comment by MartinThoma** [comment]
@AzizieAbuduaini Can you upload this PDF here?

**Comment by AzizieAbuduaini** [comment]
@MartinThoma yes I can upload the pdf. I fixed this issue by replacing "'" with "’"  before passing to generate pdf function it works for me.

**Comment by KakashiHataki-lab** [comment]
@AzizieAbuduaini Could you please detail how and where you make the substitution? Was it in your code?

**Comment by prateekdubey** [comment]
Getting this error  can anyone help me out ?


Traceback (most recent call last):
  File "C:/Users/Pratik/AppData/Local/Programs/Python/Python37/MpPscPdfScrapper.py", line 4, in <module>
    reader=PyPDF2.PdfFileReader(file)
  File "C:\Users\Pratik\AppData\Local\Programs\Python\Python37\lib\site-packages\PyPDF2\pdf.py", line 1084, in __init__
    self.read(stream)
  File "C:\Users\Pratik\AppData\Local\Programs\Python\Python37\lib\site-packages\PyPDF2\pdf.py", line 1838, in read
    assert start >= last_end
AssertionError
>>>

**Comment by prateekdubey** [comment]
Traceback (most recent call last):
  File "C:/Python/Python37/Scrapper.py", line 4, in <module>
    reader=PyPDF2.PdfFileReader(file)
  File "C:\Python\Python37\lib\site-packages\PyPDF2\pdf.py", line 1084, in __init__
    self.read(stream)
  File "C:\Python\Python37\lib\site-packages\PyPDF2\pdf.py", line 1838, in read
    assert start >= last_end
AssertionError
>>>

**Comment by MartinThoma** [comment]
I think I just had a pretty broken PDF. I'll close this issue now
