### ISSUE TITLE
Certain passwords cause UnicodeEncodeError to be thrown

### ISSUE THREAD

**Issue by yardensachs** [py-pdf/PyPDF2#402]
Hi,
Every now and again, a "passworded" document would throw `UnicodeEncodeError` when trying to encrypt. this pdf file was decrypted in Adobe Acrobat without any issues.

PDF file: http://s.ys0.co/1n1b1V0z3H0D
Password: `lGyIUdGEkjQOJ7w2rfjrTayFXT6MiarrS84ygQqrqQQT6msZLif9AhqEpbT4qPizx`

Reproduce:
```python
# Using PyPDF2==1.26.0 in Python 3.6.4 on macOS 10.13.3

import base64
from io import BytesIO
from PyPDF2 import PdfFileReader

pdf_data = base64.decodebytes(b'JVBERi0xLjMKJeLjz9MKMSAwIG9iaiAKPDwKL0Zvcm1UeXBlIDEKL1N1YnR5cGUgL0Zvcm0KL1Jl\nc291cmNlcyAKPDwKL0ZvbnQgCjw8Ci9IZWx2IDIgMCBSCj4+Ci9Qcm9jU2V0IFsvUERGIC9UZXh0\nIC9JbWFnZUIgL0ltYWdlQyAvSW1hZ2VJXQo+PgovVHlwZSAvWE9iamVjdAovQkJveCBbMCAwIDM5\nNS42OSAxNTguNTldCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9MZW5ndGggMTM1Ci9NYXRyaXggWzEg\nMCAwIDEgMCAwXQo+PgpzdHJlYW0Kekmwa5poci6k7JpCMWbxd5OKucjbcpNPQxOvgmOCG577wkhz\nLJFzfk8y15croyxhL9o289CoUHr4SXPeo308DC8tSkzU8L5eUeoR6/YYDTf/t4+49dSDgmvY020I\nxYbo86YlAJxtlV7tMpsNCdcnDkmz0wJJLBUm8rNCykg/5FtrswE9aXmsCmVuZHN0cmVhbSAKZW5k\nb2JqIAoyIDAgb2JqIAo8PAovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZwovU3VidHlwZSAvVHlw\nZTEKL1R5cGUgL0ZvbnQKL0Jhc2VGb250IC9IZWx2ZXRpY2EKPj4KZW5kb2JqIAozIDAgb2JqIAo8\nPAovS2lkcyBbNCAwIFJdCi9UeXBlIC9QYWdlcwovQ291bnQgMQo+PgplbmRvYmogCjUgMCBvYmog\nCjw8Ci9UeXBlIC9PdXRsaW5lcwovTGFzdCA2IDAgUgovRmlyc3QgNiAwIFIKL0NvdW50IDEKPj4K\nZW5kb2JqIAo2IDAgb2JqIAo8PAovVGl0bGUgKA8FjwOiaL4lEM4pCi9QYXJlbnQgNSAwIFIKL0Rl\nc3QgWzQgMCBSIC9GaXRdCj4+CmVuZG9iaiAKNyAwIG9iaiAKPDwKL0Fjcm9Gb3JtIDggMCBSCi9U\neXBlIC9DYXRhbG9nCi9QYWdlcyAzIDAgUgovT3V0bGluZXMgNSAwIFIKPj4KZW5kb2JqIAo4IDAg\nb2JqIAo8PAovRmllbGRzIFs5IDAgUl0KPj4KZW5kb2JqIAo5IDAgb2JqIAo8PAovQVAgMTAgMCBS\nCi9NSyAxMSAwIFIKL0ZUIC9UeAovREEgKGpwKz7/RFx0QP2O5jlU2LfKawJ1VSkKL1N1YnR5cGUg\nL1dpZGdldAovVHlwZSAvQW5ub3QKL1YgKLvHTjqJRH1FnoPGZ2zNKQovRiA0Ci9UICgxXT0muCkK\nL1JlY3QgWzk0LjAxODIgNDAyLjc5NyA0ODkuNzA3IDU2MS4zODldCi9CUyAxMiAwIFIKPj4KZW5k\nb2JqIAoxMCAwIG9iaiAKPDwKL04gMSAwIFIKPj4KZW5kb2JqIAoxMSAwIG9iaiAKPDwKL0JHIFsw\nLjg2ODc3NDAgMC45MDI3NzEwIDAuODYzNjMyMF0KL0JDIFswIDAgMF0KPj4KZW5kb2JqIAoxMiAw\nIG9iaiAKPDwKL1cgMwo+PgplbmRvYmogCjQgMCBvYmogCjw8Ci9Bbm5vdHMgMTMgMCBSCi9Sb3Rh\ndGUgMAovUmVzb3VyY2VzIDE0IDAgUgovVHlwZSAvUGFnZQovUGFyZW50IDMgMCBSCi9Db250ZW50\ncyAxNSAwIFIKL01lZGlhQm94IFswIDAgNjEyIDc5Ml0KPj4KZW5kb2JqIAoxMyAwIG9iaiBbOSAw\nIFJdCmVuZG9iaiAKMTQgMCBvYmogCjw8Ci9Qcm9jU2V0IFsvUERGXQo+PgplbmRvYmogCjE1IDAg\nb2JqIAo8PAovRmlsdGVyIC9GbGF0ZURlY29kZQovTGVuZ3RoIDExCj4+CnN0cmVhbQo/oGPzqhTa\nS2cGywplbmRzdHJlYW0gCmVuZG9iaiAKMTYgMCBvYmogCjw8Ci9WIDIKL0ZpbHRlciAvU3RhbmRh\ncmQKL1UgKFwoX7PqpDUXSuBVeVxiSiGHzgAAAAAAAAAAAAAAAAAAAAApCi9MZW5ndGggMTI4Ci9S\nIDMKL1AgLTEzMjQKL08gKN1C1PdIVDN1O30lUL02/PJpnbqK9yfDJE4jNHSdqDONKQo+PgplbmRv\nYmogeHJlZgowIDE3CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAw\nMDAwNDA0IDAwMDAwIG4gCjAwMDAwMDA1MDMgMDAwMDAgbiAKMDAwMDAwMTE2NSAwMDAwMCBuIAow\nMDAwMDAwNTYyIDAwMDAwIG4gCjAwMDAwMDA2MzUgMDAwMDAgbiAKMDAwMDAwMDcxMSAwMDAwMCBu\nIAowMDAwMDAwNzk0IDAwMDAwIG4gCjAwMDAwMDA4MzMgMDAwMDAgbiAKMDAwMDAwMTAzMSAwMDAw\nMCBuIAowMDAwMDAxMDY0IDAwMDAwIG4gCjAwMDAwMDExMzYgMDAwMDAgbiAKMDAwMDAwMTI5OCAw\nMDAwMCBuIAowMDAwMDAxMzIzIDAwMDAwIG4gCjAwMDAwMDEzNjMgMDAwMDAgbiAKMDAwMDAwMTQ0\nOSAwMDAwMCBuIAp0cmFpbGVyCgo8PAovSUQgWzwwYjRjMTVmNjNlNjA2NmM5MWZlY2E5ZGNiMjQx\nNDk3MT48MmZkZmJlNDc4ZGZjNTZlYWM1MjI3YjdhMTM1NGM1ODQ+XQovRW5jcnlwdCAxNiAwIFIK\nL1Jvb3QgNyAwIFIKL1NpemUgMTcKPj4Kc3RhcnR4cmVmCjE1OTkKJSVFT0YK\n')

password = 'lGyIUdGEkjQOJ7w2rfjrTayFXT6MiarrS84ygQqrqQQT6msZLif9AhqEpbT4qPizx'

PdfFileReader(BytesIO(pdf_data)).decrypt(password)
```

Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mename/.virtualenvs/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1987, in decrypt
    return self._decrypt(password)
  File "/Users/mename/.virtualenvs/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 2017, in _decrypt
    val = utils.RC4_encrypt(new_key, val)
  File "/Users/mename/.virtualenvs/venv/lib/python3.6/site-packages/PyPDF2/utils.py", line 181, in RC4_encrypt
    retval += b_(chr(ord_(plaintext[x]) ^ t))
  File "/Users/mename/.virtualenvs/venv/lib/python3.6/site-packages/PyPDF2/utils.py", line 238, in b_
    r = s.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u01a6' in position 0: ordinal not in range(256)
```

I see this failing when I run tests and they generate random passwords, so sometimes the tests will fail depending on this issue.

**Comment by yardensachs** [comment]
Example on how to generate the encrypted PDF:
I sue pdftk to encrypt.
`pdftk <any PDF file> output <new_encypted_filename.pdf> owner_pw lGyIUdGEkjQOJ7w2rfjrTayFXT6Miarr`

**To be clear:** this encryption is only for protecting editing.

```
This password fails: lGyIUdGEkjQOJ7w2rfjrTayFXT6Miarr
This password works: lGyIUdGEkjQOJ7w2rfjrTayFXT6Miar
```

**Comment by yardensachs** [comment]
Any news on this issue?

**Comment by yardensachs** [comment]
Any news on this issue?

**Comment by MartinThoma** [comment]
It seems like the issue no longer exists in PyPDF2 2.1.0

Thank you for reporting it and reminding people about it!

**Comment by MartinThoma** [comment]
Also: Awesome minimal example!
