### ISSUE TITLE
Encoding issue: PyPDF2.utils.PdfReadError: Illegal character in Name Object

### ISSUE THREAD

**Issue by gitzjm** [py-pdf/PyPDF2#438]
(已解决)我在给一个PDF添加水印的时候遇到了如下错误,提示我的Name Object中有非法字符:

```
Traceback (most recent call last):
  File "E:/test/水印/PDF水印.py", line 66, in <module>
    add_watermark("111111.pdf",r"F:\SVN代码\repository\back\ninstar_demo1\static\watermark\logo_watermark.pdf","output")
  File "E:/test/水印/PDF水印.py", line 61, in add_watermark
    pdf_output.write(output_stream)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\generic.py", line 579, in readFromStream
    value = readObject(stream, pdf)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\generic.py", line 60, in readObject
    return NameObject.readFromStream(stream, pdf)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\generic.py", line 492, in readFromStream
    raise utils.PdfReadError("Illegal character in Name Object")
PyPDF2.utils.PdfReadError: Illegal character in Name Object
```

从代码中发现文件流已经合并完成,理论上我的水印是已经加上了的,但是往文件中写入的时候抛出了异常
我发现是generic.py的484行:
return NameObject(name.decode('utf-8'))
抛出的异常,因为我的PDF是中文所以我想到是因为编码问题,于是我把utf-8改成了GBK,
但是又出现了另外一个异常:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 8-9: ordinal not in range(256)
又找到这个异常是 utils的第238行导致的:
                r = s.encode('latin-1')
又是一个编码问题,一开始我将latin-1换成了utf-8发现可以输出文件,但是文字排版错乱,而且少了许多文字,于是我想到可能是因为PDF中存在不同编码的文字导致的,所以我将此处代码改为了:

```python
            try:
                r = s.encode('latin-1')
                if len(s) < 2:
                    bc[s] = r
                return r
            except Exception as e:
                print(s)
                r = s.encode('utf-8')
                if len(s) < 2:
                    bc[s] = r
                return r
```

问题成功解决,但是我感觉还会发生其他类似的异常,希望官方能关注一下PDF不同字符编码的兼容问题.

**Comment by zhangsanfu** [comment]
the same problem

**Comment by gitzjm** [comment]
台灣的朋友你好啊~
已發 pull request ，具體修正方法如下
486行的代碼：            
`           return NameObject(name.decode('utf-8'))
`           
替換為 ：
```
            try:
                ret=name.decode('utf-8')
            except (UnicodeEncodeError, UnicodeDecodeError) as e:
                ret=name.decode('gbk')
            return NameObject(ret)
```
即可

**Comment by gitzjm** [comment]
> 我有同样的问题，你的修复对我有用。
> 你可以向作者发送拉动请求吗？
> 
> 我遇到同一个问题，您的方法可以解决我的问题。
> 您可以发一个拉请求给作者吗？
台湾的朋友你好啊〜
已发拉请求，具体修正方法如下
486行的代码：
return NameObject(name.decode('utf-8'))
替换为：

            try:
                ret=name.decode('utf-8')
            except (UnicodeEncodeError, UnicodeDecodeError) as e:
                ret=name.decode('gbk')
            return NameObject(ret)
即可

**Comment by eagleoflqj** [comment]
```python
try:
    r = s.encode('latin-1')
except:
    r = s.encode('utf-8')
if len(s) < 2:
    bc[s] = r
return r
```

**Comment by zuiyuewentian** [comment]
遇到同样问题，重新打了个包，发在这里
https://github.com/zuiyuewentian/PyPDF2/releases/tag/v1.26.1

**Comment by MartinThoma** [comment]
Do you still get the same issue with the latest PyPDF2?

Can somebody share a pdf that causes it?

**Comment by MartinThoma** [comment]
I'm closing this issue now as it might have been solved with the latest improvements. Please let me know if it wasn't solved by the latest PyPDF2 version.

Also, please share a PDF which causes issues!

**Comment by michelle-chou25** [comment]
I met the same problem again, same as the author

**Comment by zuiyuewentian** [comment]
you can see my branch project



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/24/2023 15:42 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [py-pdf/pypdf] Encoding issue: PyPDF2.utils.PdfReadError: Illegal character in Name Object (#438) |

I met the same problem again, same as the author

**Comment by pubpub-zz** [comment]
> I met the same problem again, same as the author

@michelle-chou25 
Without pdf and code we can not come complete analysis. Please open a new issue and provide the data

**Comment by lwdsw** [comment]
> 使用最新的 PyPDF2 是否仍然遇到同样的问题？
> 
> 有人可以分享导致它的pdf吗？

来 用我这个
[工艺流程图.pdf](https://github.com/py-pdf/pypdf/files/13204514/default.pdf)

**Comment by stefan6419846** [comment]
@lwdsw Please open a new issue for it with your code and the PDF file as well as an English description. Note that PyPDF2 is deprecated and should be migrated to *pypdf*.
