### ISSUE TITLE
Stream has ended unexpectedly

### ISSUE THREAD

**Issue by simonsteiner1984** [py-pdf/PyPDF2#454]
[out.pdf](https://github.com/mstamy2/PyPDF2/files/2379430/out.pdf)

```
"PyPDF2/generic.py", line 334, in readStringFromStream
    raise PdfStreamError("Stream has ended unexpectedly")
PyPDF2.utils.PdfStreamError: Stream has ended unexpectedly
```

with this code:

```python
import StringIO
from PyPDF2 import PdfFileWriter, PdfFileReader
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4

input_pdf = '../out.pdf'

ifh = file(input_pdf, 'rb')
inv_input = PdfFileReader(ifh, strict=False)

packet = StringIO.StringIO()

can = canvas.Canvas(packet, pagesize=A4)
can.drawString(10, 10, 'ADDED INFO')
can.save()

packet.seek(0)
added_info = PdfFileReader(packet)

output = PdfFileWriter()

page_count = 1
for x in range(page_count):
    page = inv_input.getPage(x)
    page.mergePage(added_info.getPage(0))
    output.addPage(page)

file_stream = file('../pypdf.pdf', 'wb')
output.write(file_stream)
file_stream.close()
```

**Comment by vdmitriyev** [comment]
I experience the same error for some of my PDF files

```text
  File "/.venv/lib/python3.6/site-packages/PyPDF2/utils.py", line 134, in readUntilRegex
    raise PdfStreamError("Stream has ended unexpectedly")
PyPDF2.utils.PdfStreamError: Stream has ended unexpectedly
```

**Comment by MartinThoma** [comment]
I can confirm for `PyPDF2==1.27.7` with the above example:

```
Traceback (most recent call last):
  File "/home/moose/foo.py", line 22, in <module>
    page.mergePage(added_info.getPage(0))
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 2423, in mergePage
    self._mergePage(page2)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 2460, in _mergePage
    newContentArray.append(PageObject._pushPopGS(
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 2384, in _pushPopGS
    stream = ContentStream(contents, pdf)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 2871, in __init__
    self.__parseContentStream(stream)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 2903, in __parseContentStream
    operands.append(readObject(stream, None))
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 84, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 181, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 90, in readObject
    return readStringFromStream(stream)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 349, in readStringFromStream
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly
```

**Comment by MartinThoma** [comment]
Simplifying it a bit:

```python
from PyPDF2 import PdfFileWriter, PdfFileReader


def prepare_stream():
    from io import BytesIO
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4

    packet = BytesIO()
    can = canvas.Canvas(packet, pagesize=A4)
    can.drawString(10, 10, "ADDED INFO")
    can.save()
    packet.seek(0)
    return packet


reader = PdfFileReader("out.pdf", strict=False)
writer = PdfFileWriter()

page = reader.getPage(0)

stream = prepare_stream()
added_info = PdfFileReader(stream)
to_merge = added_info.getPage(0)
page.mergePage(to_merge)
writer.addPage(page)

writer.write("pypdf.pdf")
```

**Comment by MartinThoma** [comment]
I guess the issue is that PyPDF2 tries to read the stream twice - once for `getPage` and then again for `mergePage`. If this is the issue, then it is a bug in PyPDF2.

**Comment by MartinThoma** [comment]
I can confirm it for `PyPDF2==2.4.2`:

```
Traceback (most recent call last):
  File "foo.py", line 26, in <module>
    page.merge_page(to_merge)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 449, in merge_page
    self._merge_page(page2, expand=expand)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 514, in _merge_page
    PageObject._push_pop_gs(original_content, self.pdf)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 384, in _push_pop_gs
    stream = ContentStream(contents, pdf)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1177, in __init__
    self.__parse_content_stream(stream_bytes)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1207, in __parse_content_stream
    operands.append(read_object(stream, None, self.forced_encoding))
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1314, in read_object
    return ArrayObject.read_from_stream(stream, pdf, forced_encoding)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 217, in read_from_stream
    arr.append(read_object(stream, pdf, forced_encoding))
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1318, in read_object
    return read_string_from_stream(stream, forced_encoding)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 434, in read_string_from_stream
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly
```
