### ISSUE TITLE
ValueError: invalid literal for int() with base 10: b'obj'

### ISSUE THREAD

**Issue by cabhijith** [py-pdf/PyPDF2#540]
Hi, 
I am using the following code to extract the info. I get a Value Error. I have checked previous issues but could not find a solution. 

Code: 
```python
from PyPDF2 import PdfFileReader

def extract_information(pdf_path):
    with open(pdf_path, 'rb') as f:
        pdf = PdfFileReader(f)
        information = pdf.getDocumentInfo()
        number_of_pages = pdf.getNumPages()


    return information

if __name__ == '__main__':
    path = 'March_5_8000/1.pdf'
    extract_information(path)
```
I have also attached the PDF file throwing the error. 
[1.pdf](https://github.com/mstamy2/PyPDF2/files/4292903/1.pdf)

**Comment by MartinThoma** [comment]
I can confirm for PyPDF==1.27.7:

```
Traceback (most recent call last):
  File "/home/moose/foo.py", line 14, in <module>
    extract_information(path)
  File "/home/moose/foo.py", line 6, in extract_information
    information = pdf.getDocumentInfo()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1225, in getDocumentInfo
    obj = self.trailer[TK.INFO]
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 539, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 191, in getObject
    return self.pdf.getObject(self).getObject()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1724, in getObject
    idnum, generation = self.readObjectHeader(self.stream)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1798, in readObjectHeader
    return int(idnum), int(generation)
ValueError: invalid literal for int() with base 10: b'obj'
```

Also with `strict=False`. 

There is 

```
idnum=b'obj'
generation=b'2'
```

**Comment by MartinThoma** [comment]
This issue no longer occurs with `strict=False` and PyPDF2==2.4.2
