### ISSUE TITLE
Getting Assertion error while reading the PDF file

### ISSUE THREAD

**Issue by KrishnaThali** [py-pdf/PyPDF2#554]
I am getting the below error when I try to read a PDF file which has images and tables in it.

**Code:**

```
from PyPDF2 import PdfFileReader
import os

os.chdir(<Path to dir>)

pdf_document = 'sample.pdf' 
pdf = PdfFileReader(pdf_document,'rb') **#Error here**
```

**Error:**

```
Traceback (most recent call last):
  File "/home/krishna/PycharmProjects/AI_DRC/DRM_read.py", line 9, in <module>
    pdf = PdfFileReader(filehandle)
  File "/home/krishna/PycharmProjects/AI_DRC/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/krishna/PycharmProjects/AI_DRC/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1838, in read
    assert start >= last_end
AssertionError
```

**NOTE: File is 18 MB in size**

**Comment by MartinThoma** [comment]
Can you share the PDF?

**Comment by MartinThoma** [comment]
If anybody gets the same mistake, please open a new issue and fill out the questionnaire
