### ISSUE TITLE
Unexpected zlib.error on malformed PDF

### ISSUE THREAD

**Issue by Google-Autofuzz** [py-pdf/PyPDF2#586]
When running the following code with the latest pypi version of PyPDF2 on the attached input results in an unexpected `zlib.error`:

```python
import sys
import PyPDF2

pdf = PyPDF2.PdfFileReader(sys.argv[1], strict=False, warndest=None,
                        overwriteWarnings=False)

pdf.getDocumentInfo()
pdf.getFields()
pdf.getNamedDestinations()
pdf.getNumPages()
pdf.getOutlines()
pdf.getPageLayout()
pdf.getPageMode()
pdf.getXmpMetadata()
```

```python
$ python3 pypdf2_repro.py ../test.pdf
Traceback (most recent call last):
  File "pypdf2_repro.py", line 4, in <module>
    pdf = PyPDF2.PdfFileReader(sys.argv[1], strict=False, warndest=None,
  File "/home/user/.local/lib/python3.8/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/user/.local/lib/python3.8/site-packages/PyPDF2/pdf.py", line 1807, in read
    streamData = BytesIO(b_(xrefstream.getData()))
  File "/home/user/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 841, in getData
    decoded._data = filters.decodeStreamData(self)
  File "/home/user/.local/lib/python3.8/site-packages/PyPDF2/filters.py", line 346, in decodeStreamData
    data = FlateDecode.decode(data, stream.get("/DecodeParms"))
  File "/home/user/.local/lib/python3.8/site-packages/PyPDF2/filters.py", line 111, in decode
    data = decompress(data)
  File "/home/user/.local/lib/python3.8/site-packages/PyPDF2/filters.py", line 49, in decompress
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: invalid distance too far back
$ 
```

[test.pdf](https://github.com/mstamy2/PyPDF2/files/5537001/test.pdf)

**Comment by MartinThoma** [comment]
For `PyPDF2==1.27.7`:

```Traceback (most recent call last):
  File "issue586.py", line 4, in <module>
    overwriteWarnings=False)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1208, in __init__
    self.read(stream)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 2010, in read
    raise PdfReadError("Could not find xref table at specified location")
PyPDF2.errors.PdfReadError: Could not find xref table at specified location
```

**Comment by MartinThoma** [comment]
As neither Evince nor the PDF Reader of Google Chrome are able to open that PDF, I think it's broken to an extend that is simply not fixable.
