### ISSUE TITLE
ValueError: key must be PdfObject

### ISSUE THREAD

**Issue by CoolbreezeKevin** [py-pdf/PyPDF2#648]
```
Traceback (most recent call last):

  File "F:\QLDownload\newworkpath\code\PDFcomand.py", line 19, in <module>
    file_merger.write("merge.pdf")

  File "D:\Anaconda3\lib\site-packages\PyPDF4\merger.py", line 220, in write
    self.output.addPage(page.pagedata)

  File "D:\Anaconda3\lib\site-packages\PyPDF4\pdf.py", line 138, in addPage
    self._addPage(page, list.append)

  File "D:\Anaconda3\lib\site-packages\PyPDF4\pdf.py", line 124, in _addPage
    page[NameObject("/Parent")] = self._pages

  File "D:\Anaconda3\lib\site-packages\PyPDF4\generic.py", line 513, in __setitem__
    raise ValueError("key must be PdfObject")

ValueError: key must be PdfObject
```

**Comment by MartinThoma** [comment]
Do you have example code + a PDF that shows the issue?

**Comment by MartinThoma** [comment]
I'm closing this now as it might have been solved. If anybody stubles over this issue with a recent PyPDF2 version, please add an example PDF / example code / the Traceback.

**Comment by Cameron-Leech-Thomson** [comment]
Hey, I'm pretty sure it's just because I'm doing something wrong but I can't seem to change the value of an annotation, and end up with the same error:
```
Traceback (most recent call last):
  File "D:\Documents\Other Projects\D&D Bot\Discord.py\example_bot.py", line 133, in on_message
    success = setField(path + attachment.filename, messageValues[1], messageValues[2])
  File "D:\Documents\Other Projects\D&D Bot\Discord.py\pdfReader.py", line 63, in setField
    annotation["/V"] = value
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic\_data_structures.py", line 136, in __setitem__
    raise ValueError("key must be PdfObject")
ValueError: key must be PdfObject
```

The code that caused the error is:
```python
def setField(path, key, value):
    success = False
    pdf = PyPDF2.PdfFileReader(path)
    
    writer = PyPDF2.PdfFileWriter()
    writer.clone_document_from_reader(pdf)
    
    for i in range(writer.getNumPages()):
        if "/Annots" in writer.pages[i]:
            # Get annotations from page:
            for anno in writer.pages[i]["/Annots"]:
                annotation = anno.get_object()
                # Check if the target exists in the annotations:
                if key.lower() == str(annotation["/T"]).strip().lower().replace(' ', ''):
                    # Update the field:
                    if "/V" in annotation:
                        print(type(annotation["/V"]))
                        annotation["/V"] = value           <------ here
                        writer.add_annotation(i, annotation)
                        success = True
    
    if (success):
        with open (path, 'wb') as output_stream:
            writer.write(output_stream)
    
    return success
```

If there's an easier way to change the value of an annotation I'd love to know, but this is about as good as I could manage.

The PDF I'm using is attached. Thanks
[Cammyyy_79897300.pdf](https://github.com/py-pdf/PyPDF2/files/9697388/Cammyyy_79897300.pdf)

**Comment by pubpub-zz** [comment]
the PyPDF2 annotations need to be NameObject and values needs also to be converted (here to FloatObject if this is a FixedPrint):
`annotation[PyPDF2.generic.NameObject("/V")] = PyPDF2.generic.FloatObject(value)`

**Comment by shafeeralip** [comment]
getting error `key must be PdfObject'`

`
image = input_pdf.pages[page_number]
image['/Resources']['/ProcSet'] = ['/PDF', '/Text', '/ImageB', '/ImageC', '/ImageI']
output_pdf.add_page(image)
`

**Comment by stefan6419846** [comment]
Please open a new issue and fill the complete issue template.
