### ISSUE TITLE
BUG: a self-triggered deprecation warning in PyPDF2 1.28

### ISSUE THREAD

**Issue by neutrinoceros** [py-pdf/PyPDF2#890]
I found a self-triggered deprecation warning while running tests for a project I maintain which depends on PyPDF2. We treat warnings as errors in our CI.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-12.3.1-x86_64-i386-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
1.28.1
```

## Code

This is a minimal, complete example that shows the issue:

```python
# t.py
from PyPDF2 import PdfReader, PdfMerger

merger = PdfMerger()
merger.append(PdfReader("example.pdf", "rb"))
```

Running `python -Werror t.py` raises:
```python-traceback
Traceback (most recent call last):
  File "/Users/robcleme/dev/friends/AMICAL/t.py", line 6, in <module>
    merger.append(PdfReader(ifile, "rb"))
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/PyPDF2/merger.py", line 234, in append
    self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/PyPDF2/merger.py", line 133, in merge
    if isString(fileobj):
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/PyPDF2/_utils.py", line 76, in isString
    warnings.warn(DEPR_MSG_NO_REPLACEMENT.format("isString"))
UserWarning: isString is deprecated and will be removed in PyPDF2 2.0.0.
```
So the warning is triggered from `PyPDF2.merger.py`, meaning some internal functionalities are still relying on deprecated API, but it's out of my control to deal with it from the user side.

## PDF

any pdf works as `example.pdf` here.
I suggest maintainers to start treating warnings as errors in PyPDF2's CI so this kind of problem can be detected ahead of releases.

**Comment by MartinThoma** [comment]
Thanks for the report. I'll take care of it this evening (in ~10 hours)

**Comment by MartinThoma** [comment]
Treating warnings as errors for PyPDF2 internally would mean that we don't test the functions which are about to be deprecated. Might be a valid way to do it, but I'm uncertain about it.

Nicest would be to capture / annotate warnings. Basically the test should know if a warning is expected and treat a non-expected warning (or a missing expected warning) as a failure.

**Comment by neutrinoceros** [comment]
> Treating warnings as errors for PyPDF2 internally would mean that we don't test the functions which are about to be deprecated. Might be a valid way to do it, but I'm uncertain about it.

In pytest you can use `pytest.warns` to test deprecation warnings are correctly triggered. Configuring pytest to treat warnings as errors still works !

**Comment by MasterOdin** [comment]
In addition to #891 which fixes the specific issue raised here, I've also opened #892 to make the test suite more strict about making sure there are no warnings raised that are not wrapped with `pytest.warns`. I plan to make some additional PRs around that to focus on cleaning up specific classes of warnings (e.g. replacing `reader.numPages` usage in tests with `len(reader.pages)`) to keep the git commit cleaner / more linear until #892 passes, at which point I'll mark that one as ready to merge.

**Comment by MartinThoma** [comment]
I hope those issues are fixed now: https://github.com/py-pdf/PyPDF2/releases/tag/1.28.2
