### ISSUE TITLE
ValueError: Unresolved bookmark

### ISSUE THREAD

**Issue by xilopaint** [py-pdf/PyPDF2#956]
I'm trying to split a PDF file but my code snippet only works if I use `PdfMerger.append` with `import_bookmarks=False`, otherwise I get the following error:

```
Traceback (most recent call last):
  File "/Users/xxx/sample.py", line 10, in <module>
    merger.append(reader, pages=page_range)
  File "/Users/xxx/PyPDF2/_merger.py", line 254, in append
    self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
  File "/Users/xxx/PyPDF2/_merger.py", line 180, in merge
    self._associate_bookmarks_to_pages(srcpages)
  File "/Users/xxx/PyPDF2/_merger.py", line 595, in _associate_bookmarks_to_pages
    raise ValueError("Unresolved bookmark '{}'".format(b["/Title"]))
ValueError: Unresolved bookmark 'xxxxx xxxxxxxxx'
```

## Environment

```bash
$ python -m platform
macOS-12.4-x86_64-i386-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.1.0
```

## Code

```python
from PyPDF2 import PdfReader, PdfMerger, PageRange

reader = PdfReader("sample.pdf")

num_pages = len(reader.pages)
page_ranges = [PageRange(slice(n, n + 200)) for n in range(0, num_pages, 200)]

for n, page_range in enumerate(page_ranges, 1):
    merger = PdfMerger()
    merger.append(reader, pages=page_range)
    merger.write(f"{'sample'} [{'part'} {n}].pdf")
```

## PDF

Unfortunately, I can't share the PDF file.

**Comment by MartinThoma** [comment]
Thank you for reporting the issue :heart: 

I will make a release to PyPI on Sunday which contains the PR by @mtd91429 .

As you mentioned, the PR fixes it. I have no way of checking that, so please let me know if I should re-open this issue :-)
