### ISSUE TITLE
 Linearized PDF with degraded trailer gives "KeyError: '/Root'" 

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/PyPDF2#989]
When trying to extract the text from a PDF, I get an exception.

## Environment

```bash
$ python -m platform
Linux-5.4.0-113-generic-x86_64-with-glibc2.31

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.2.0
```

## MCVE: PDF + Code

Using this PDF: https://corpora.tika.apache.org/base/docs/govdocs1/989/989691.pdf

```python
from PyPDF2 import PdfReader
reader = PdfReader("pdf/989691.pdf")  # PdfReadWarning: incorrect startxref pointer(1)
reader.pages[0].extract_text()
```

I get this traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 1462, in __getitem__
    len_self = len(self)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 1453, in __len__
    return self.length_function()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 362, in _get_num_pages
    self._flatten()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 929, in _flatten
    catalog = self.trailer[TK.ROOT].get_object()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 623, in __getitem__
    return dict.__getitem__(self, key).get_object()
KeyError: '/Root'
```

**Comment by pubpub-zz** [comment]
The issue with those document is that they are Linearized PDF with degraded trailer : It is not linked with text_extraction.
@MartinThoma  can you rename the issue and change tags. interpretation on appendix F should be extended

**Comment by pubpub-zz** [comment]
actually the linear section is invalid, and looking carefully in the pdf, the startxref is invalid. PyPDF2 then rebuild the xref table, and use the last trailer, but this one does not contain the /root key.
To fix this, I've rescam the whole pdf and updates/rebuild the trailer
